### TESTING USER CONTROLLER

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "login" : "danil",
  "password" : "1234"
}

###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "login" : "admin",
  "password" : "admin"
}

###

#GET http://localhost:8080/api/v1/users/danil
#Authorization: Basic ZGFuaWw6MTIzNA==

### TESTING PRODUCT CONTROLLER

POST http://localhost:8080/api/v1/products
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "name" : "tee",
  "cost" : "29.99"
}

###

POST http://localhost:8080/api/v1/products
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
"name" : "cap",
"cost" : "20.50"
}

###   !!! SHOULD PASS RIGHT ID !!!

PATCH http://localhost:8080/api/v1/products/5
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{
  "name" : "UPDATED-cap",
  "cost" : "20.50"
}

###

GET http://localhost:8080/api/v1/products

###

DELETE http://localhost:8080/api/v1/products/4
Authorization: Basic YWRtaW46YWRtaW4=

### TESTING ORDER CONTROLLER

POST http://localhost:8080/api/v1/orders/3
Authorization: Basic ZGFuaWw6MTIzNA==
###

DELETE http://localhost:8080/api/v1/orders/6
Authorization: Basic ZGFuaWw6MTIzNA==
###

GET http://localhost:8080/api/v1/orders
Authorization: Basic ZGFuaWw6MTIzNA==