### testing user controller

POST http://localhost:8080/users
Content-Type: application/json

{
  "login" : "danil",
  "password" : "1234"
}

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "login" : "tim",
  "password" : "1234"
}

###

GET http://localhost:8080/users/danil

1234

### testing product controller

POST http://localhost:8080/products
Content-Type: application/json

{
  "name" : "tee",
  "cost" : "29.99"
}

###

POST http://localhost:8080/products
Content-Type: application/json

{
"name" : "cap",
"cost" : "20.50"
}

###

PATCH http://localhost:8080/products/1
Content-Type: application/json

{
  "name" : "UPDATED-cap",
  "cost" : "20.50"
}

###

GET http://localhost:8080/products

###

DELETE http://localhost:8080/products/1

### testing order controller

POST http://localhost:8080/orders/0

danil

###

POST http://localhost:8080/orders

danil

###

DELETE http://localhost:8080/orders/0

danil

###